Repository Caleydo/gapminder, pull requests merged in 2020-01, with the labels that each got.

#58 Update to Python 3.7
  .circleci/config.yml
  .travis.yml
Labels: type: refactor

#56 Update node version
  .circleci/config.yml
Labels: type: refactor

#59 Initialize i18next
  src/index.ts
Labels: release: minor, type: feature

#60 Release 2.0.0
  .circleci/config.yml
  .gitignore
  .travis.yml
  .yo-rc.json
  buildInfo.js
  deploy/Dockerfile
  deploy/nginx-default.conf
  karma.conf.js
  package.json
  phovea_registry.js
  src/gapminder.ts
  src/index.ts
  tests.webpack.js
  tsconfig.json
  tsconfig_dev.json
  tsd.d.ts
  tslint.json
  webpack.config.js
Labels: release: major
